#ifndef INSTR_H
#define INSTR_H

#include "dogarm.h"
#include <stdint.h>

typedef dogarm_instruction_type_t instr_type_t;

#define INSTR_TYPE_UNDEFINED DOGARM_INSTR_TYPE_UNDEFINED
#define INSTR_TYPE_DATA_PROC DOGARM_INSTR_TYPE_DATA_PROC
#define INSTR_TYPE_MULTIPLY DOGARM_INSTR_TYPE_MULTIPLY
#define INSTR_TYPE_MULTIPLY_LONG DOGARM_INSTR_TYPE_MULTIPLY_LONG
#define INSTR_TYPE_SINGLE_DATA_TRANSFER DOGARM_INSTR_TYPE_SINGLE_DATA_TRANSFER
#define INSTR_TYPE_HALFWORD_DATA_TRANSFER DOGARM_INSTR_TYPE_HALFWORD_DATA_TRANSFER
#define INSTR_TYPE_BLOCK_DATA_TRANSFER DOGARM_INSTR_TYPE_BLOCK_DATA_TRANSFER
#define INSTR_TYPE_BRANCH DOGARM_INSTR_TYPE_BRANCH
#define INSTR_TYPE_SOFTWARE_INTERRUPT DOGARM_INSTR_TYPE_SOFTWARE_INTERRUPT
#define INSTR_TYPE_COPROCESSOR DOGARM_INSTR_TYPE_COPROCESSOR
#define INSTR_TYPE_SWAP DOGARM_INSTR_TYPE_SWAP
#define INSTR_TYPE_PSR_TRANSFER DOGARM_INSTR_TYPE_PSR_TRANSFER
#define INSTR_TYPE_BRANCH_EXCHANGE DOGARM_INSTR_TYPE_BRANCH_EXCHANGE
#define INSTR_TYPE_WIDE_IMMEDIATE DOGARM_INSTR_TYPE_WIDE_IMMEDIATE

typedef struct {
    uint32_t raw;
    uint32_t address;
    instr_type_t type;
    uint32_t cond;
    dogarm_arch_t arch;
    dogarm_branch_format_t branch_format;
    dogarm_syntax_t syntax;
} instruction_t;

#endif
